import { test, expect } from '@playwright/test';
import sharp from 'sharp';
import { randomUUID, randomBytes, createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';

test('upload, remembered nickname, privacy, admin filters and ZIP', async ({ page, browser, request }) => {
 const errors = []; page.on('pageerror', e => errors.push(e.message));
 const nickname = `테스터-${randomUUID().slice(0,8)}`;
 await page.goto('/');
 await expect(page.getByRole('heading', {name:'조직이식결과서를 업로드해주세요.'})).toBeVisible();
 expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
 await page.getByLabel('의료기관명', {exact:true}).fill(nickname);
 await page.getByRole('button',{name:'저장',exact:true}).click();
 await page.reload();
 await expect(page.getByLabel('의료기관명',{exact:true})).toHaveValue(nickname);
 const image = await sharp({create:{width:80,height:60,channels:3,background:'#759d80'}}).jpeg().toBuffer();
 await page.route('**/api/photos/scale-*/thumb', route => route.fulfill({contentType:'image/jpeg',body:image}));
 await page.locator('#files').setInputFiles([{name:'한글-사진.jpg',mimeType:'image/jpeg',buffer:image},{name:'second.jpg',mimeType:'image/jpeg',buffer:image}]);
 await expect(page.locator('.queue-item')).toHaveCount(2);
 await page.getByRole('button',{name:'업로드',exact:true}).click();
 await expect(page.locator('.photo-card')).toHaveCount(2);
 await expect(page.locator('#queue')).toContainText('완료');
 await expect(page.locator('.photo-card img').first()).toHaveJSProperty('naturalWidth',80);
 const photoId = await page.locator('[data-open]').first().getAttribute('data-open');
 expect((await request.get(`/api/photos/${photoId}/thumb`)).status()).toBe(401);
 expect((await request.get('/api/admin/photos')).status()).toBe(401);
 await page.locator('[data-open]').first().click();
 const ownDownload = page.waitForEvent('download');
 await page.getByText('원본 다운로드 ↓',{exact:true}).click();
 expect((await ownDownload).suggestedFilename()).toMatch(/\.jpg$/);
 await page.locator('#viewer .close').click();
 const other = await browser.newContext(); const otherPage = await other.newPage();
 await otherPage.goto('http://127.0.0.1:3107/'); await expect(otherPage.locator('.photo-card')).toHaveCount(0); await other.close();
 await page.goto('/admin');
 await page.getByLabel('관리자 비밀번호').fill('wrong'); await page.getByRole('button',{name:'로그인'}).click();
 await expect(page.getByRole('alert')).toHaveText('비밀번호를 확인해 주세요.');
 await page.getByLabel('관리자 비밀번호').fill('test-password-strong'); await page.getByRole('button',{name:'로그인'}).click();
 await page.getByRole('button',{name:'링크 · QR ↗'}).click();
 await expect(page.locator('#qr')).toHaveAttribute('src',/^data:image\/png/);
 await expect(page.locator('#share-url')).toHaveValue('http://127.0.0.1:3107/');
 await page.locator('#share-dialog .close').click();
 await page.getByLabel('업로드 시작일').fill('2020-01-01');
 await page.getByLabel('업로드 종료일').fill('2099-12-31');
 await page.getByLabel('의료기관명 검색').fill(nickname); await page.getByRole('button',{name:'조회',exact:true}).click();
 await expect(page.locator('.photo-card')).toHaveCount(2);
 await page.locator('[data-select]').first().check();
 const zipDownload=page.waitForEvent('download'); await page.getByRole('button',{name:'선택한 1장 다운로드 ↓'}).click();
 const zip = await zipDownload;
 expect(zip.suggestedFilename()).toBe('moa-photos.zip');
 expect(await zip.failure()).toBeNull();
 const zipBytes = readFileSync(await zip.path());
 expect(zipBytes.subarray(0,2).toString()).toBe('PK');
 expect(zipBytes.readUInt16LE(zipBytes.length-12)).toBe(1);
 await page.getByLabel('의료기관명 검색').fill('존재하지않는의료기관명'); await page.getByRole('button',{name:'조회',exact:true}).click();
 await expect(page.locator('.photo-card')).toHaveCount(0);
 await expect(page.locator('#download')).toBeDisabled();
 expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
 await page.getByRole('button',{name:'로그아웃'}).click();
 await expect(page.getByLabel('관리자 비밀번호')).toBeVisible();
 expect(errors).toEqual([]);
});

test('30 real-sized JPEGs upload with three in flight and preserve original bytes', async ({ page, request }, testInfo) => {
 test.setTimeout(120000);
 const errors=[];page.on('pageerror', e=>errors.push(e.message));
 await page.goto('/');
 await page.getByLabel('의료기관명',{exact:true}).fill('30장검증치과');
 const image=await sharp(randomBytes(1600*1600*3),{raw:{width:1600,height:1600,channels:3}}).jpeg({quality:90}).toBuffer();
 expect(image.length).toBeGreaterThan(1900000);expect(image.length).toBeLessThan(2500000);
 const files=Array.from({length:30},(_,i)=>{const file=testInfo.outputPath(`결과서-${i+1}.jpg`);writeFileSync(file,image);return file;});
 const active=new Set();let peak=0;
 page.on('request',r=>{if(r.method()==='POST' && r.url().endsWith('/api/photos')){active.add(r);peak=Math.max(peak,active.size);}});
 // Responses release upload slots before Playwright emits requestfinished.
 page.on('response',r=>active.delete(r.request()));page.on('requestfailed',r=>active.delete(r));
 await page.locator('#files').setInputFiles(files);
 await page.getByRole('button',{name:'업로드',exact:true}).click();
 await expect(page.locator('.photo-card')).toHaveCount(30,{timeout:90000});
 await expect(page.locator('.queue-item .error')).toHaveCount(0);
 await expect(page.getByRole('button',{name:'더 업로드하기'})).toBeVisible();
 expect(peak).toBeLessThanOrEqual(3);
 const id=await page.locator('[data-open]').first().getAttribute('data-open');
 const visitor=await page.evaluate(()=>localStorage.getItem('moa-visitor'));
 const original=await request.get(`/api/photos/${id}/original`,{headers:{'X-Visitor-Id':visitor}});
 expect(original.status()).toBe(200);
 expect(createHash('sha256').update(await original.body()).digest('hex')).toBe(createHash('sha256').update(image).digest('hex'));
 expect(errors).toEqual([]);
});

test('50,000 records paginate, combine institution/date range and sort', async ({ request }) => {
 await request.post('/api/admin/login',{data:{password:'test-password-strong'}});
 const first=await (await request.get('/api/admin/photos?institution=규모검증')).json();
 expect(first.total).toBe(50000);expect(first.photos).toHaveLength(60);expect(first.pages).toBe(834);
 expect(first.bytes).toBe(95000000000);expect(first.institutions).toBe(100);
 const last=await (await request.get('/api/admin/photos?institution=규모검증&page=834')).json();
 expect(last.photos).toHaveLength(20);
 expect(new Set([...first.photos,...last.photos].map(p=>p.id)).size).toBe(80);
 const ranged=await (await request.get('/api/admin/photos?institution=규모검증&from=2026-01-02&to=2026-01-03&sort=oldest')).json();
 expect(ranged.total).toBe(2880);
 expect(ranged.photos[0].created).toBe('2026-01-01T15:00:00.000Z');
 const lastRange=await (await request.get('/api/admin/photos?institution=규모검증&from=2026-01-02&to=2026-01-03&sort=oldest&page=48')).json();
 expect(lastRange.photos.at(-1).created).toBe('2026-01-03T14:59:00.000Z');
 const combined=await (await request.get('/api/admin/photos?institution=규모검증-001&from=2026-01-02&to=2026-01-03')).json();
 expect(combined.total).toBe(29);expect(combined.photos.every(p=>p.nickname==='규모검증-001치과')).toBeTruthy();
 expect(combined.overall).toEqual(first.overall);
 expect(last.overall).toEqual(first.overall);
 const sorted=await (await request.get('/api/admin/photos?institution=규모검증&sort=institution')).json();
 expect(sorted.photos.every(p=>p.nickname==='규모검증-000치과')).toBeTruthy();
 const reverse=await (await request.get('/api/admin/photos?institution=규모검증&sort=institution-desc')).json();
 expect(reverse.photos.every(p=>p.nickname==='규모검증-099치과')).toBeTruthy();
});

test('global stats stay unfiltered and manual refresh preserves the applied search', async ({page,request}) => {
 test.setTimeout(60000);
 const institution='자동갱신-'+randomUUID().slice(0,8);
 const buffer=await sharp({create:{width:12,height:12,channels:3,background:'white'}}).jpeg().toBuffer();
 const uploadAs = async name => {
  const response=await request.post('/api/photos',{headers:{'X-Visitor-Id':randomUUID()},multipart:{institution:name,requestId:randomUUID(),photo:{name:'result.jpg',mimeType:'image/jpeg',buffer}}});
  expect(response.status()).toBe(201);return response.json();
 };
 const first=await uploadAs(institution);
 await page.route('**/api/photos/scale-*/thumb',route=>route.fulfill({contentType:'image/jpeg',body:buffer}));
 await page.goto('/admin');
 await page.getByLabel('관리자 비밀번호').fill('test-password-strong');
 await page.getByRole('button',{name:'로그인',exact:true}).click();
 await expect(page.locator('#total')).not.toHaveText('0');
 const total=Number(await page.locator('#total').textContent());
 const institutions=Number(await page.locator('#people').textContent());
 const volume=await page.locator('#volume').textContent();
 await page.getByLabel('의료기관명 검색').fill(institution);
 await page.getByRole('button',{name:'조회',exact:true}).click();
 await expect(page.locator('.photo-card')).toHaveCount(1);
 await expect(page.locator('#total')).toHaveText(String(total));
 await expect(page.locator('#people')).toHaveText(String(institutions));
 await expect(page.locator('#volume')).toHaveText(volume);
 await page.locator(`[data-select="${first.id}"]`).check();
 // A half-edited search must not silently replace the applied filter on refresh.
 await page.getByLabel('의료기관명 검색').fill('아직조회하지않은검색어');
 await uploadAs(institution);
 await page.getByRole('button',{name:'새로고침',exact:true}).click();
 await expect(page.locator('.photo-card')).toHaveCount(2,{timeout:12000});
 await expect(page.locator('#total')).toHaveText(String(total+1));
 await expect(page.locator(`[data-select="${first.id}"]`)).toBeChecked();
 await expect(page.getByLabel('의료기관명 검색')).toHaveValue('아직조회하지않은검색어');
 await uploadAs(institution+'-다른기관');
 await page.getByLabel('의료기관명 검색').fill(institution);
 await page.getByLabel('업로드 종료일').fill('2000-01-01');
 await page.getByRole('button',{name:'조회',exact:true}).click();
 await expect(page.locator('.photo-card')).toHaveCount(0);
 await expect(page.locator('#total')).toHaveText(String(total+2));
 await uploadAs(institution+'-새기관');
 await page.getByRole('button',{name:'새로고침',exact:true}).click();
 await expect(page.locator('#total')).toHaveText(String(total+3),{timeout:12000});
 await expect(page.locator('#people')).toHaveText(String(institutions+2));
 await expect(page.locator('.photo-card')).toHaveCount(0);
 await page.request.post('/api/admin/logout');
 await page.getByRole('button',{name:'새로고침',exact:true}).click();
 await expect(page.getByLabel('관리자 비밀번호')).toBeVisible();
});

test('reject fake photos and deduplicate a retried upload', async ({ request }) => {
 const headers={'X-Visitor-Id':randomUUID()};
 const invalid = await request.post('/api/photos',{headers,multipart:{nickname:'검증',requestId:randomUUID(),photo:{name:'fake.jpg',mimeType:'image/jpeg',buffer:Buffer.from('not an image')}}});
 expect(invalid.status()).toBe(415);
 const buffer=await sharp({create:{width:5,height:5,channels:3,background:'red'}}).png().toBuffer();
 const payload={headers,multipart:{nickname:'검증',requestId:randomUUID(),photo:{name:'real.png',mimeType:'image/png',buffer}}};
 const first=await request.post('/api/photos',payload);expect(first.status()).toBe(201);
 const second=await request.post('/api/photos',payload);expect(second.status()).toBe(200);
 expect((await first.json()).id).toBe((await second.json()).id);
 expect((await (await request.get('/api/photos/mine',{headers})).json()).photos.length).toBe(1);
 const crossOrigin=await request.post('/api/admin/login',{headers:{Origin:'https://elsewhere.example'},data:{password:'test-password-strong'}});
 expect(crossOrigin.status()).toBe(403);
});
